name: "Auto Assign"
description: "Assign issues automatically based on labels."
inputs:
  github_token:
    description: "GitHub access token"
    required: true
    default: ""
runs:
  using: node12
  main: "src/index.js"